import Head from "next/head";
import Loading from "@/Components/Loading";
import Greating from "@/Components/greating/Greating";
import Image from "next/image";
import Link from "next/link";
import {useEffect, useState} from "react";

const Catalog = ({posts}:any) => {
    const [isSearch, setIsSearch] = useState(false)
    const [politics, setPolitics] = useState<number>(0)
    const [writers, setWriters] = useState<number>(0)
    const [businessman, setBusinessman] = useState<number>(0)
    const [advo, setAdvo] = useState<number>(0)
    const [sci, setSci] = useState<number>(0)
    const [acti, setActi] = useState<number>(0)
    const [moti, setMoti] = useState<number>(0)
    const [act, setAct] = useState<number>(0)
    const [filo, setFilo] = useState<number>(0)
    const [isPoliticsAdded, setIsPoliticsAdded] = useState(false)

    useEffect(() => {
        if(posts){
            if(!isPoliticsAdded){
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'политик'? setPolitics(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'писатель'? setWriters(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'бизнесмен'? setBusinessman(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'адвокат'? setAdvo(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'ученный'? setSci(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'активист'? setActi(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'мотиватор'? setMoti(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'актер'? setAct(oldState => oldState+1): null) )
                posts.filter((element: any) => element.type.filter((subType: any) => subType === 'филосов'? setFilo(oldState => oldState+1): null) )
                setIsPoliticsAdded(true)
                setPolitics(oldState => Math.floor(oldState / 2))
            }
        }
    }, [posts])
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="flex justify-center items-start decoration-black min-h-screen max-w-7xl mx-auto">
                    <>
                        {/*{isPopUp && <Greating/>}*/}
                        <div className="flex flex-col w-full ">
                            <div className="py-6 px-4 mb-16 w-full">
                                <nav>
                                    <ul className="flex items-center">
                                        <li className="mr-auto">
                                            <h3 className="font-bold text-2xl">Parable</h3>
                                        </li>
                                        <li className="flex items-center mr-2.5">
                                            <div className={`searching flex items-center gap-1 h-full ${isSearch? "active-search" : null}`}>
                                                <button onClick={() => setIsSearch(oldState => !oldState)} className="w-fit cursor-pointer">
                                                    {!isSearch ? (
                                                            <svg width="28" height="28" viewBox="0 0 28 28" fill="none"
                                                                 xmlns="http://www.w3.org/2000/svg">
                                                                <path
                                                                    d="M16.9268 17.0401L20.4 20.4001M19.28 11.4401C19.28 15.77 15.7699 19.2801 11.44 19.2801C7.11006 19.2801 3.59998 15.77 3.59998 11.4401C3.59998 7.11019 7.11006 3.6001 11.44 3.6001C15.7699 3.6001 19.28 7.11019 19.28 11.4401Z"
                                                                    stroke="black" strokeWidth="2" stroke-linecap="round"/>
                                                            </svg>):
                                                        (
                                                            <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                <path d="M18 6L6 18M18 18L6 6" stroke="black" strokeWidth="2" stroke-linecap="round"/>
                                                            </svg>
                                                        )
                                                    }
                                                </button>
                                                <input type="text" className={`search_input ${isSearch? "active-search" : null}`}/>
                                            </div>
                                        </li>
                                        <li className="flex items-center">
                                            <button>
                                                <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M11.4951 2.71381C11.7017 2.29527 12.2985 2.29527 12.5051 2.71381L15.1791 8.13194C15.2611 8.29814 15.4196 8.41334 15.6031 8.43999L21.5823 9.30883C22.0442 9.37595 22.2286 9.94357 21.8944 10.2694L17.5678 14.4868C17.4351 14.6162 17.3745 14.8026 17.4058 14.9852L18.4272 20.9403C18.5061 21.4004 18.0233 21.7512 17.6101 21.534L12.2621 18.7224C12.0981 18.6361 11.9021 18.6361 11.738 18.7224L6.39002 21.534C5.97689 21.7512 5.49404 21.4004 5.57294 20.9403L6.59432 14.9852C6.62565 14.8026 6.56509 14.6162 6.43236 14.4868L2.10573 10.2694C1.7715 9.94357 1.95594 9.37595 2.41783 9.30883L8.39708 8.43999C8.5805 8.41334 8.73906 8.29814 8.82109 8.13194L11.4951 2.71381Z" stroke="black" strokeWidth="2" stroke-linejoin="round"/>
                                                </svg>
                                            </button>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <h1 className="font-bold text-3xl mb-12">Каталог</h1>

                            <div className="flex gap-5 mb-5">
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от политиков</h3>
                                        <p className="text-neutral-600 text-xl">{politics} притчь</p>
                                    </div>
                                    <Image src="/assets/piano.svg" alt="icon-piano" width={220} height={220}/>
                                </div>
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от бизнесменов</h3>
                                        <p className="text-neutral-600 text-xl">{businessman} притчь</p>
                                    </div>
                                    <Image src="/assets/plan.svg" alt="icon-plan" width={220} height={220}/>
                                </div>
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от писателей</h3>
                                        <p className="text-neutral-600 text-xl">{writers} притчь</p>
                                    </div>
                                    <Image src="/assets/search.svg" alt="icon-piano" width={220} height={220}/>
                                </div>
                            </div>

                            <div className="flex gap-5 mb-5">
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от адвокатов</h3>
                                        <p className="text-neutral-600 text-xl">{advo} притчь</p>
                                    </div>
                                    <Image src="/assets/seo.svg" alt="icon-piano" width={220} height={220}/>
                                </div>
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от ученных</h3>
                                        <p className="text-neutral-600 text-xl">{sci} притчь</p>
                                    </div>
                                    <Image src="/assets/welcome.svg" alt="icon-plan" width={200} height={200}/>
                                </div>
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от активистов</h3>
                                        <p className="text-neutral-600 text-xl">{acti} притчь</p>
                                    </div>
                                    <Image src="/assets/success.svg" alt="icon-piano" width={220} height={220}/>
                                </div>
                            </div>

                            <div className="flex gap-5 mb-24">
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от мотиваторов</h3>
                                        <p className="text-neutral-600 text-xl">{moti} притчь</p>
                                    </div>
                                    <Image src="/assets/vision.svg" alt="icon-piano" width={220} height={220}/>
                                </div>
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от актеров</h3>
                                        <p className="text-neutral-600 text-xl">{act} притчь</p>
                                    </div>
                                    <Image src="/assets/yoga.svg" alt="icon-plan" width={200} height={200}/>
                                </div>
                                <div className="flex p-6 gap-16 items-center bg-indigo-100 w-1/3 rounded-2xl">
                                    <div className="flex flex-col gap-5 w-1/2">
                                        <h3 className="font-bold text-lg">Притча от филосовов</h3>
                                        <p className="text-neutral-600 text-xl">{filo} притчь</p>
                                    </div>
                                    <Image src="/assets/teaching.svg" alt="icon-piano" width={200} height={200}/>
                                </div>
                            </div>


                        </div>
                    </>
            </div>
        </>
    )
}

export default Catalog


export async function getServerSideProps(){
    try {
        const res = await fetch(`https://parable.vercel.app/data.json`);
        // const res = await fetch(`http://localhost:3000/data.json`);
        const data = await res.json();

        return {
            props: {
                posts: data.posts
            }
        };
    } catch (error) {
        // console.error(error);
        return {
            props: {}
        };
    }
}